/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutFeatures: typeof import('./components/About/Features.vue')['default']
    AboutHobbies: typeof import('./components/About/Hobbies.vue')['default']
    AboutSkills: typeof import('./components/About/Skills.vue')['default']
    AboutSocial: typeof import('./components/About/Social.vue')['default']
    AboutStatistics: typeof import('./components/About/Statistics.vue')['default']
    AboutUses: typeof import('./components/About/Uses.vue')['default']
    AppButton: typeof import('./components/App/Button.vue')['default']
    AppDialog: typeof import('./components/App/Dialog.vue')['default']
    AppDropdown: typeof import('./components/App/Dropdown.vue')['default']
    AppImg: typeof import('./components/App/Img.vue')['default']
    AppLoading: typeof import('./components/App/Loading.vue')['default']
    AppSwiper: typeof import('./components/App/Swiper.vue')['default']
    Article: typeof import('./components/Article.vue')['default']
    ArticleCard: typeof import('./components/Article/Card.vue')['default']
    ArticleCardHome: typeof import('./components/Article/CardHome.vue')['default']
    ArticleToc: typeof import('./components/Article/Toc.vue')['default']
    FieldText: typeof import('./components/Field/Text.vue')['default']
    FieldToggle: typeof import('./components/Field/Toggle.vue')['default']
    FormContact: typeof import('./components/Form/Contact.vue')['default']
    HomeArticle: typeof import('./components/Home/Article.vue')['default']
    HomeGallery: typeof import('./components/Home/Gallery.vue')['default']
    HomeHero: typeof import('./components/Home/Hero.vue')['default']
    HomeHistory: typeof import('./components/Home/History.vue')['default']
    HomeHistoryItem: typeof import('./components/Home/HistoryItem.vue')['default']
    HomeNewsletter: typeof import('./components/Home/Newsletter.vue')['default']
    HomeOpenSource: typeof import('./components/Home/OpenSource.vue')['default']
    HomeSocial: typeof import('./components/Home/Social.vue')['default']
    HomeTitle: typeof import('./components/Home/Title.vue')['default']
    LayoutContainer: typeof import('./components/Layout/Container.vue')['default']
    LayoutFooter: typeof import('./components/Layout/Footer.vue')['default']
    LayoutHeader: typeof import('./components/Layout/Header/Index.vue')['default']
    LayoutHeaderNavbar: typeof import('./components/Layout/Header/Navbar.vue')['default']
    LayoutHeaderOptions: typeof import('./components/Layout/Header/Options/Index.vue')['default']
    LayoutHeaderOptionsColorSwitch: typeof import('./components/Layout/Header/Options/ColorSwitch.vue')['default']
    LayoutHeaderOptionsLocaleSwitch: typeof import('./components/Layout/Header/Options/LocaleSwitch.vue')['default']
    LayoutPage: typeof import('./components/Layout/Page.vue')['default']
    LayoutSidebar: typeof import('./components/Layout/Sidebar.vue')['default']
    ProjectCard: typeof import('./components/Project/Card.vue')['default']
    ProjectDevelopers: typeof import('./components/Project/Developers.vue')['default']
    ProjectLink: typeof import('./components/Project/Link.vue')['default']
    ProjectTechnologies: typeof import('./components/Project/Technologies.vue')['default']
    ProjectTechnologiesList: typeof import('./components/Project/TechnologiesList.vue')['default']
    ProjectTechnology: typeof import('./components/Project/Technology.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TypedLink: typeof import('./components/TypedLink.vue')['default']
  }
}
