---
services:
  portfolio_dev:
    container_name: portfolio_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: portfolio_dev
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
