---
services:
  portfolio_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio
    env_file: .env
    restart: always

  nginx:
    image: nginx:latest
    container_name: portfolio-nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/error.html:/usr/share/nginx/html/error.html
    depends_on:
      - portfolio_app
    restart: always
